# server port ???!!
server:
  port: 8002

# build ???? ??? +Mysql, mybatis ?! ???,
# driver config  // ? MySQL??? ???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

# ? mybatis / MenuMapper.xml ?? ???
mybatis:
  mapper-locations: mappers/**/*.xml

  # ?? -  **: ?? ??,?? ?????? ????!    * : ???